### ISSUE TITLE
Remove "data" image in css to prevent CSP img-src conflicts

### ISSUE THREAD

**Issue by LazaroOnline** [single-spa/import-map-overrides#113]
The "import-map-overrides" UI has an embedded image in its [CSS here](https://github.com/single-spa/import-map-overrides/blob/2928ab6e8184323eb093babf9819e7e69d054751/src/ui/import-map-overrides.css#L161).

This is a problem because those images does not load in pages that have enabled the recommended [Content-Security-Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) (CSP) headers that uses the [img-src](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/img-src) directive to enforce images to load only from a white list of valid domains and prevents loading images from "data:" to mitigate XSS attacks where an attacker could inject html to deface a vulnerable website, with such CSP configuration, the attackers would not be able to load images even if they could inject arbitrary html.

Apart from not loading those images, another problem is that a page using "import-map-overrides" and that "CSP" would generate a corresponding error in the browser's DevTools console and send a [CSP report](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/report-to) that can flood the CSP logs.

Here is an example of a CSP directive in the html meta tags in case you want to test it:
```html
<html>
<head>
<!-- Remove this <meta> tag to see the page without image restrictions -->
<meta http-equiv="Content-Security-Policy" content="img-src https://MY-DOMAIN.COM;"/>
<style>
.thing {
	height: 215px;
	width: 260px;
	background-image: url("data:image/svg+xml;charset=utf8,%3Csvg width='261' height='216' xmlns='http://www.w3.org/2000/svg' stroke='%23ffffff' stroke-linecap='square' stroke-miterlimit='10' shape-rendering='auto' stroke-opacity='1' fill='%23ffffff' stroke-dasharray='none' stroke-width='1' stroke-linejoin='miter' stroke-dashoffset='0'%3E%3Cg%3E%3Cpath fill='%23ffffff' d='m152.5625,214.0625q-27.5625,0 -49.6406,-11.8125q-22.0781,-11.8125 -34.7344,-28.4062l12.6563,-11.5313q10.6874,15.1875 31.0781,25.0313q20.3906,9.8437 40.6406,9.8437q21.375,0 44.1563,-11.5313q22.7812,-11.5312 34.3124,-34.3124q11.5313,-22.7813 11.5313,-44.1563q0,-21.375 -11.5313,-44.1563q-11.5312,-22.7812 -34.3124,-34.3124q-22.7813,-11.5313 -44.1563,-11.5313q-19.9687,0 -39.6563,9.1406q-19.6874,9.1407 -30.9374,24.1875q-11.25,15.0469 -16.7344,35.7188l42.3281,-34.7344l-54,91.6875l-54,-91.6875l47.25,38.8125q3.9375,-24.4687 17.4375,-44.5781q13.5,-20.1094 36.9844,-32.7656q23.4844,-12.6563 51.3281,-12.6563q29.25,0 54,14.0625q24.75,14.0625 38.8125,38.8125q14.0625,24.75 14.0625,54q0,29.25 -14.0625,54q-14.0625,24.75 -38.8125,38.8125q-24.75,14.0625 -54,14.0625z' /%3E%3C/g%3E%3C/svg%3E");
}
</style>
</head>
<body style="background-color: gray;">
<div>Test CSP Headers IMG Data</div>
<br/>Example using img data in css:
<br/><div class="thing"></div>
<br/>Example using img data in html:
<br/><img alt="red-square" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIj4KICA8cmVjdCB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgc3R5bGU9ImZpbGw6cmVkOyIgLz4KPC9zdmc+" />
</body>
</html>
```
<img width="800" alt="image" src="https://github.com/user-attachments/assets/9d1de99c-582b-41b4-9ce7-30790b9f4087">

## Solution
This project only has that 1 image that needs remediation.
The image seems to be a loading spinner, this could be replaced by pure CSS without requiring a source image/svg at all.
Take a look at any of these CSS loaders:
https://loading.io/css/  
https://css-loaders.com/

**Comment by joeldenning** [comment]
Fix released in https://github.com/single-spa/import-map-overrides/releases/tag/v4.0.1
