### ISSUE TITLE
How does this library avoid insecure content warnings

### ISSUE THREAD

**Issue by northkode** [single-spa/import-map-overrides#125]
Recently I was working on something locally where it did something similar to this package but allowing the browser to load a file from a local runner server to override content on the page.. 

The problem was that the site was getting a insure request and we had to unblock the browser to allow the localhost:PORT file to run off http

How does this library avoid such a warning? We are using this to load off http locally but the browser never complains and in fact still shows that the site is secure.

**Comment by joeldenning** [comment]
Browser warnings are out of the control of import-map-overrides. For loading locally hosted modules over HTTPS, you can generate a TLS certificate and tell your operating system to trust it, to avoid insecure warnings.
