### ISSUE TITLE
Page refresh required to reflect changes

### ISSUE THREAD

**Issue by HemTech** [single-spa/import-map-overrides#34]
I have tried to override app url but it does reflect change until you refresh the page. can we update it without refreshing a page?

Step: 1 : update the url
Step 2: navigate between app
it will load the old url only
Step 3; refresh the page
it will now load the update url

Purpose : want to update url runtime whenever new version of app deployed on server

**Comment by joeldenning** [comment]
The import maps spec strictly forbids this behavior ([docs](https://github.com/WICG/import-maps#installation)):

> As another consequence of how import maps affect all imports, attempting to add a new <script type="importmap"> after any module graph fetching has started is an error. The import map will be ignored, and the <script> element will fire an error event.

Contrary to the spec, SystemJS provides a few APIs that support modifying the module registry without reloading the page. Specifically, System.delete](https://github.com/systemjs/systemjs/blob/master/docs/api.md#systemdeleteid---boolean) plus a subsequent `System.import()` will cause the module to be downloaded again.

Additionally, in the last several days, SystemJS has considered deviating from the spec to allow for direct import map updates. See https://github.com/systemjs/systemjs/pull/2215, https://github.com/systemjs/systemjs/issues/2211, and https://github.com/guybedford/import-maps-extensions.

I'm open to this feature being added to import-map-overrides, but there are a few edge cases that might become tricky, as this is essentially hot reloading of modules. One question for you - are you using import-map-overrides for local development purposes, or for managing deployments? I would strongly discourage using it as a deployment mechanism.

**Comment by robmosca** [comment]
This issue seems to be stale. With the current vision about moving towards ESM, I believe we can close it, for the time being. @HemTech, please, feel free to add comments in case you want it to be reopened.
