### ISSUE TITLE
Failed to execute `attachShadow` on `Element` in 3.0.0

### ISSUE THREAD

**Issue by nilzona** [single-spa/import-map-overrides#66]
In the new version 3 I'm getting the following console error

```console
Uncaught DOMException: Failed to execute 'attachShadow' on 'Element': Shadow root cannot be created on a host which already hosts a shadow tree.
    at a.value (https://cdn.jsdelivr.net/npm/import-map-overrides@3.0.0/dist/import-map-overrides.js:2:45424)
    at a.value (https://cdn.jsdelivr.net/npm/import-map-overrides@3.0.0/dist/import-map-overrides.js:2:45188)
```

This shows up when I am using `single-spa-react` to render one react microfrontend on the page.

Is there a way to avoid that? @ralphsaunders  maybe you have an idea? It's most likely related to https://github.com/joeldenning/import-map-overrides/pull/65

**Comment by OriolInvernonLlaneza** [comment]
We have the same problem on page load.

**Comment by OriolInvernonLlaneza** [comment]
It looks like the issue comes from the element already having a shadow root attached. It makes `attachShadow` throw [InvalidStateError exception](https://developer.mozilla.org/en-US/docs/Web/API/Element/attachShadow#exceptions).

I made a PR that just checks if it is already created, it seems to work fine but maybe I didn't take something into account.

**Comment by smilyanp** [comment]
We have the same problem

**Comment by moderndegree** [comment]
I am seeing the same error. @joeldenning, is there any chance we can get someone to look at this?

**Comment by lhtdesignde** [comment]
Seeing the same thing. Happens at `value:function(){this.shadow=this.attachShadow({mode:"open"})`
Works fine in 2.4.2. Would be great to get this fixed seeing that it's around for some time. 
@joeldenning any way we could help here?

**Comment by SergioTx** [comment]
Same error here with version 3.0.0.

**Comment by adripanico** [comment]
Any update on this?

**Comment by Achilles1515** [comment]
Workaround until fixed:

```html
<!-- <import-map-overrides-full show-when-local-storage="overrides-ui"></import-map-overrides-full> -->
<script>
	const imo = document.createElement('import-map-overrides-full', { is: 'import-map-overrides-full' });
	imo.setAttribute('show-when-local-storage', 'overrides-ui');
	const attachShadowOriginal = imo.attachShadow;
	imo.attachShadow = function (options) {
		return this.shadowRoot ? this.shadowRoot : attachShadowOriginal.apply(this, [options]);
	};
	document.body.appendChild(imo);
</script>
```

**Comment by piwysocki** [comment]
@joeldenning , can you release v3.0.1 with a fix?

**Comment by robmosca** [comment]
This has been released. Closing it.
