### ISSUE TITLE
Is there a way to disable Auto Dev Lib Override?

### ISSUE THREAD

**Issue by luismiguelprs** [single-spa/import-map-overrides#70]
Hi!

I`m working on a project with angular and I faced a problem when trying to import angular dependencies.
My project is using angular v13 and when I set angular at systemjs-importmap it replaces the import with the last version (14) automatically.
Is there a way to disable it?

**Comment by ekbaumgarten** [comment]
Please check if your import-map-overrides-full element contains the **dev-libs** attribute. 
Removing this attribute should work.

You can also set the import-map-overrides-dev-libs item in your localStorage to false.

**Comment by robmosca** [comment]
This issue has an answer. Closing it.
