### ISSUE TITLE
how can i create E2E cypress tests?

### ISSUE THREAD

**Issue by misaku** [single-spa/import-map-overrides#71]
how can i create E2E cypress tests?

**Comment by filoxo** [comment]
Have you reviewed our documentation on e2e testing? https://single-spa.js.org/docs/testing/e2e/ 
Any specific details you still have questions for?

**Comment by misaku** [comment]
i would like example config cypress and single spa

**Comment by filoxo** [comment]
We don't have any examples for this. If you create one, please do share with the us and the wider single-spa community!

**Comment by filoxo** [comment]
Any community contributed examples for this are welcome!
