### ISSUE TITLE
Hi, I have this error in the console : Shadow root cannot be created on a host which already hosts a shadow tree. 

### ISSUE THREAD

**Issue by NoreddineRadi** [single-spa/import-map-overrides#73]
I think it has a relation with the last version "3.0.0". 
I don't have the error with this version 2.4.2
![image](https://user-images.githubusercontent.com/32415616/204494821-1e87eab9-a985-4341-ba1f-16a239497603.png)

**Comment by projectcss** [comment]
Hello, I have encountered the same problem. Have you solved it

**Comment by projectcss** [comment]
> I think it has a relation with the last version "3.0.0". I don't have the error with this version 2.4.2 ![image](https://user-images.githubusercontent.com/32415616/204494821-1e87eab9-a985-4341-ba1f-16a239497603.png)

Hello, I have encountered the same problem. Have you solved it

**Comment by NoreddineRadi** [comment]
Hi, I didn't find a solution for the latest version : "3.0.0" but you can use the oldest version 2.4.2, in that  case the error disappears.

**Comment by Mariotutal** [comment]
Hi, someone has already found a fix for this issue?

**Comment by webJose** [comment]
Same here.  The funny thing is, it was working just fine yesterday.  Today simply refuses to work.

**Comment by rdlagemann** [comment]
@robmosca thanks for addressing the Issue 👏🏼  Do you know when we can expect to have a new deployed version with this bug fix?

**Comment by robmosca** [comment]
Hi @rdlagemann, I am not a maintainer unfortunately. I would suggest you write to the #maintainers channel in Slack. Based on my previous experience, releases on this package do not happen very often.

**Comment by robmosca** [comment]
This has been released. Closing the issue.
