### ISSUE TITLE
Is it possible to support SystemJS and native imports at the same time?

### ISSUE THREAD

**Issue by robinrossow** [single-spa/import-map-overrides#74]
Hey,

I recently switched to vite and I'm trying to get my override to work with the default dev mode in vite, which is using native imports. 
I'm using SystemJS for all my other microservices and I don't understand if it is even possible to be able to run both at the same time. 

When I try to override my main.js from vite I get the following error:
`Uncaught SyntaxError: Cannot use import statement outside a module (at main.js:1:1)`

Is it somehow possible to have both, native imports and SystemJS running at the same time?

**Comment by filoxo** [comment]
No, not with SystemJS. From their documentation:

> SystemJS does not support direct integration with the native ES module browser loader because there is no way to share dependencies between the module systems. For extending the functionality of the native module loader in browsers, see [ES module Shims](https://github.com/guybedford/es-module-shims), which like SystemJS, provides workflows for import maps and other modules features, but on top of base-level modules support in browsers, which it does using a fast Wasm-based source rewriting to remap module specifiers.

https://github.com/systemjs/systemjs#systemjs-babel

Also, this has been on my mind: https://github.com/single-spa/single-spa.js.org/issues/538#issuecomment-1099330535 and I've not gotten a satisfactory answer. For now, the solution is to go all-in on ESM but the ecosystem isn't at the point where we can safely push people to do so (eg. React does not provide an ESM build). 

There are very good reasons to keep [dev/prod parity](https://12factor.net/dev-prod-parity) and vite does not cater to this paradigm unless you as a consumer opt into all-esm.
