### ISSUE TITLE
Add configuration to control where the UI button is positioned

### ISSUE THREAD

**Issue by robmosca** [single-spa/import-map-overrides#78]
In our application the UI button covers another element on the page:

![Screenshot 2023-04-26 at 10 56 29](https://user-images.githubusercontent.com/60132064/234525825-c951adc6-4728-4260-a99c-7a36343e926d.png)
![Screenshot 2023-04-26 at 10 56 02](https://user-images.githubusercontent.com/60132064/234525828-8d2999bd-d38f-4947-bf3b-750e35aae64b.png)

It would be great to have some configuration to be able to move it to another corner.

I am actually happy to work on it when I have a bit of time.

**Comment by JanAckermann1337** [comment]
As a workaround, you can include a CSS file into your app which is restyling the trigger. For example if you want it in the top right corner

```
.imo-trigger {
    top: 0;
}
```

**Comment by robmosca** [comment]
Hi @JanAckermann1337 ,
Thanks for the suggestion. We are indeed loading it only in our development environment.
I tried overriding the styles but couldn't make it work. Not sure why (is it possible that the styles are scoped to the element through Shadow DOM?)
Will try to give it another go.

**Comment by JanAckermann1337** [comment]
Not that I know of. I got it working for our project. I can add some snippets tomorrow which might help.

**Comment by robmosca** [comment]
I've looked into it and while adding CSS works on version 2.2.0, it won't work in version 3.0.0. It's actually even mentioned in the release notes... (I realized it later) 😅 
![Screenshot 2023-04-26 at 23 39 46](https://user-images.githubusercontent.com/60132064/234709011-6c5166b9-e6e4-4490-a835-ac156857cf67.png)
I got to override that with something like this:
```
    <script>
      document
        .querySelector('import-map-overrides-full')
        .shadowRoot.querySelector('.imo-trigger')
        .setAttribute('style', 'left: 0;')
    </script>
```
but it is a really hacky solution and I would prefer to introduce a cleaner solution with an attribute like `position`, for example.
