### ISSUE TITLE
Attribute trigger-position does not have any effect

### ISSUE THREAD

**Issue by webJose** [single-spa/import-map-overrides#92]
Not much more to add:  If I add `<import-map-overrides-full trigger-position="top-left"></import-map-overrides-full>` to my page, the button still appears in the bottom right corner.

If you need any more details or a repro, let me know.

**Comment by robmosca** [comment]
Hi @webJose, I don't think this feature has been released yet. I would kindly suggest you write in the #maintainers channel in Slack to see if any of the maintainers can release a new version of the package.

**Comment by webJose** [comment]
Thanks, @robmosca, for the heads-up.

**Comment by robmosca** [comment]
It has been released
